### ISSUE TITLE
change label of fahrplan link

### ISSUE THREAD

**Issue by saerdnaer** [TIBHannover/c3voc_avp_import#4]
The `fahrplan.events.ccc.de` label in following code snipped should be automatically extracted from the link variable  

https://github.com/TIBHannover/c3voc_avp_import/blob/799e5ac404c5589538b3fcb343025785bfbf5071/get_videos_and_xml.py#L196-L198

For example at  https://av.tib.eu/media/43569 it should be labeled `https://talks.2019.foss4g.org/`
<img width="1109" alt="temp" src="https://user-images.githubusercontent.com/40266/66159565-8a025600-e628-11e9-9411-9c4a6afe15b5.png">

**Comment by cenetp** [comment]
Fixed :)
